### ISSUE TITLE
Install from PyPi wheel failing with syntax errors for _multiparty_solving_inner.cpp

### ISSUE THREAD

**Issue by joel-williams** [data61/anonlink#253]
Hi, trying to install anonlink from PyPI ("pip install anonlink" on Win 10 with Python 3.8) and it tries to compile Anonlink, then fails with syntax errors for _multiparty_solving_inner.cpp
Any suggestions here?

**Comment by joel-williams** [comment]
[anonlink_install_output.txt](https://github.com/data61/anonlink/files/3862320/anonlink_install_output.txt)

**Comment by wilko77** [comment]
Anonlink 0.12.5, the version on pypi does not support Windows (because of the C++ compilation thing). 
Windows support will be part of the next release. In the meantime,
you can try installing from the current *master* branch, as we recently added support for Windows compilation.
Azure does now also build windows wheel files, but currently only for Python 3.6 and 3.7. You can find the wheels here: https://dev.azure.com/data61/Anonlink/_build/results?buildId=744&view=results

**Comment by joel-williams** [comment]
Thanks wilko77, the 3.7 windows wheel from the build pipeline worked fine.
